# Day 1 Session 1

In [1]:
print("Hello World!")

Hello World!


In [6]:
# person weight 100 lbs and 61 inches
w=100*0.453592
h=61*0.0254
bmi = w/(h*h)
print(bmi)

18.89462526573535


In [4]:
h_p=[61, 62, 65, 63, 67] # height of 5 people in inches
w_p=[100, 200, 160, 180, 123] # weight of 5 people in lbs

In [5]:
import numpy as np
array_hp=np.array(h_p)
array_hp=array_hp*0.0254 # Broadcasting
array_hp

array([1.5494, 1.5748, 1.651 , 1.6002, 1.7018])

In [12]:
array_wp=np.array(w_p)
array_wp=array_wp*0.453592 # Broadcasting
array_wp

array([45.3592  , 90.7184  , 72.57472 , 81.64656 , 55.791816])

In [14]:
bmi=array_wp/(array_hp*array_hp)
bmi

array([18.89462527, 36.58007316, 26.62509846, 31.8852157 , 19.26431004])

In [16]:
# 1 Dimension
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(len(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1
(10,)
10


In [19]:
# 2 Dimension
b=np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))
print(b.ndim)
print(b.shape)
print(len(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
2


In [20]:
# 2 Dimension
c=np.array([[10, 11], [20, 21], [30, 31]])
print(c)
print(type(c))
print(c.ndim)
print(c.shape)
print(len(c))

[[10 11]
 [20 21]
 [30 31]]
<class 'numpy.ndarray'>
2
(3, 2)
3


In [23]:
np.random.randint(1,10,5) # parameter (start value, ending value, no. of values)

array([4, 3, 5, 8, 6])

In [28]:
x=np.array([12,12,13,14,14,13,13,13,12,12])
np.unique(x, return_counts=True) # select method and press shift+tab it will show parameters

CPU times: total: 0 ns
Wall time: 0 ns


(array([12, 13, 14]), array([4, 4, 2], dtype=int64))

In [30]:
# Dot Product
A=np.array([[1, 2, 3], [4, 5, 6]])
B=np.array([[7, 8], [9, 10], [11, 12]])
C=np.dot(A,B)
C

array([[ 58,  64],
       [139, 154]])

In [31]:
A@B

array([[ 58,  64],
       [139, 154]])

In [35]:
x=np.random.randint(1,10,10)
print(x)
p1=np.power(x,2)
print(p1)

[7 6 4 5 5 1 2 8 3 5]
[49 36 16 25 25  1  4 64  9 25]


In [43]:
# Euclidean Distance
m=np.array([1, 3])
n=np.array([4, 6])
o=np.array(m-n) # np.subtract(a,b)
sq=np.power(o, 2) # np.square(o)
res=np.sum(sq)
dist=np.sqrt(res)
dist

4.242640687119285

In [46]:
# Normalization 
ans=np.sqrt(np.sum(np.power(np.subtract(np.array([1, 3]), np.array([4, 6])), 2)))
ans

4.242640687119285

In [48]:
age=np.array([23, 34, 55, 34, 56])
sal=np.array([12000, 30000, 40000, 25000, 45000])
scaled_age=(age-np.min(age))/(np.max(age)-np.min(age))
print(scaled_age)
scaled_sal=(sal-np.min(sal))/(np.max(sal)-np.min(sal))
print(scaled_sal)

[0.         0.33333333 0.96969697 0.33333333 1.        ]
[0.         0.54545455 0.84848485 0.39393939 1.        ]


In [12]:
# Mean Square Error
ypred1=np.array([1100, 2100, 1900]) # predicted value
ypred2=np.array([1050, 2050, 1950]) # predicted value
yreal=np.array([1000, 2000, 2000]) # expected value
error=np.subtract(ypred, yreal)
error

array([ 100,  100, -100])

In [7]:
s_error=np.square(error)
s_error

array([10000, 10000, 10000], dtype=int32)

In [8]:
m_s_error=np.mean(s_error)
m_s_error

10000.0

In [10]:
res1=np.mean(np.square(np.subtract(ypred1, yreal)))
res1

10000.0

In [13]:
res2=np.mean(np.square(np.subtract(ypred2, yreal)))
res2

2500.0